version: "3.9"

services:
  db:
    image: mongo
  redis:
    image: redis
  server:
    build: .
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/pub:ro
    ports:
      - 9999:80
